AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPCFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref MyVPC
      ResourceType: VPC
      TrafficType: ALL
      LogDestinationType: s3
      LogDestination: !Ref FlowLogsBucket
      LogFormat: '${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}'
  FlowLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'my-flow-logs-bucket'

Resources:
  S3VPCEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref MyVPC
      RouteTableIds:
        - !Ref PrivateRouteTable
  DynamoDBVPCEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcId: !Ref MyVPC
      RouteTableIds:
        - !Ref PrivateRouteTable


Resources:
  MyEBSVolume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: 20
      AvailabilityZone: us-west-2a
      Encrypted: true   # Enable encryption



Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-xxxxxxxxxxxxx  # Specify your desired AMI ID
      InstanceType: t2.micro  # Specify your desired instance type
      SecurityGroupIds:
        - sg-xxxxxxxxxxxxxx  # Specify your security group ID
      SubnetId: subnet-xxxxxxxxxxxx  # Specify your subnet ID
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y  # Update package repositories
          yum install -y httpd  # Install Apache web server
          systemctl start httpd  # Start Apache
          systemctl enable httpd  # Enable Apache to start on boot
      


